### ISSUE TITLE
Stats Tracking/Randomized Messages

### ISSUE THREAD

**Issue by raziell74** [nwesterhausen/valheim-discordconnector#10]
Not really an issue, more of a feature request. My friends and I were talking about how cool it would be if the bot would keep track of certain stats like how many times each of us has died or logged in and had the ability to display that in a the discord message. 

We were also thinking it would be really great if you could randomize the messages. Like have a bunch of different messages for when someone logs in/out or dies. 

Just some food for thought as you build this awesome bot out :) thank you for your hard work!

**Comment by nwesterhausen** [comment]
Thanks for the suggestions!

Randomly choosing from a list of messages should be something I can implement relatively easily.

The stats thing, I could see that working as a message from the server on  a trigger, like someone logs in or dies and the server could tag on a message of how many times. Or on startup or a time send some total stats for everyone, but right now the way the messages get sent is one directional. Always from the game server to discord. I like the idea of it working like a bot and ask for stats but for right now I don't see how to simply accomplish that. I could listen on the game server chat for a specific message to work as a trigger to send stats to discord. And of course, for all of this I have to add some stat tracking into the mix.

**Comment by raziell74** [comment]
I was thinking it could keep a yml file on the server with counts, or to keep it simple you could keep the counts in a config or something as an encoded string. Not many people will be looking at config files on a server haha. I appreciate you taking the time to read our ideas. Really looking forward to how this evolves :D

**Comment by nwesterhausen** [comment]
Yeah the plan at the moment is to store the counts in a json file on the server, since I"m already pulling in a library for json serialization. Trying to figure out the "best practice" place to put it. Probably in the game directory since it isn't really configuration related and is just data used when running the server.

**Comment by nwesterhausen** [comment]
Just released 0.5.0 with randomized messages. Stats tracking will be later this week.

**Comment by raziell74** [comment]
Awesome work nwesterhausen! I saw the change log this morning, you're a wizard :) thank you for your hard work.

**Comment by nwesterhausen** [comment]
I appreciate it! You're welcome. I still have to include the stats inside the messages but they are being tracked as of version 0.5.1.
