### ISSUE TITLE
Changes in Toggles config is ignored

### ISSUE THREAD

**Issue by eeeBs** [nwesterhausen/valheim-discordconnector#104]
```
[Toggles.Messages]

## If enabled, this will send a message to Discord when the server launches.
# Setting type: Boolean
# Default value: true
Server Launch Notifications = false

## If enabled, this will send a message to Discord when the server has loaded the map and is ready for connections.
# Setting type: Boolean
# Default value: true
Server Loaded Notifications = false

## If enabled, this will send a message to Discord when the server begins shut down.
# Setting type: Boolean
# Default value: true
Server Stopping Notifications = false

## If enabled, this will send a message to Discord when the server has shut down.
# Setting type: Boolean
# Default value: true
Server Shutdown Notifications = false

## If enabled, this will send a message to Discord when the server saves the world.
# Setting type: Boolean
# Default value: true
Server World Save Notifications = false
```

But every time someone joins, Discord is still getting spammed. 
![NtVcwpw](https://user-images.githubusercontent.com/7885880/165842469-58ecf9e9-08db-4f9e-935a-2223af08f5fa.png)

Is there not a flag for the startup message?

**Comment by nwesterhausen** [comment]
Everything in the code indicates that it respects those messages.

Are you confirmed using 1.5.3 and reloading the server after modifying the config? This is the excerpt from my `games.nwest.valheim.discordconnector-toggles.cfg` I used to test:

```cfg
[Toggles.Messages]

## If enabled, this will send a message to Discord when the server launches.
# Setting type: Boolean
# Default value: true
Server Launch Notifications = false

## If enabled, this will send a message to Discord when the server has loaded the map and is ready for connections.
# Setting type: Boolean
# Default value: true
Server Loaded Notifications = false

## If enabled, this will send a message to Discord when the server begins shut down.
# Setting type: Boolean
# Default value: true
Server Stopping Notifications = false

## If enabled, this will send a message to Discord when the server has shut down.
# Setting type: Boolean
# Default value: true
Server Shutdown Notifications = false

## If enabled, this will send a message to Discord when the server saves the world.
# Setting type: Boolean
# Default value: true
Server World Save Notifications = false
```

**Comment by eeeBs** [comment]
![KR80tk6](https://user-images.githubusercontent.com/7885880/165869857-dc73086a-2e9f-421f-936e-d3a7ac3c3ded.png)

The server has been running the entire time. It's only when someone connects to the empty server that the messages are displayed, even though they are disabled in the config. 

Also, neither shout messages or discord messages are being transmitted in either direction. Anything else I can send to help trouble shoot?

**Comment by nwesterhausen** [comment]
It's almost like the plugin is installed on the client and sending all those messages.

Also this app doesn't send discord messages to the Valheim server, but it should be sending shouts from the server to Discord (it should be enabled by default). 

I suggest restarting the server since you mentioned its running the whole time. That way we can be sure it loads the configs correctly. And I suggest making sure that your clients do not have a `Webhook URL` set in `games.nwest.valheim.discordconnector.cfg`, so that we can rule out the clients sending messages.

**Comment by PaloAlo** [comment]
Ive had the same issue with latest version 1.6.1 but i have not yet restarted the server. I will try that and report back to see if it stops it from sending certain messages

**Comment by nwesterhausen** [comment]
If all you do is replace the plugin, it won't load it until the server is restarted. While the server is running, all the plugins are kept in memory and aren't reloaded.
