### ISSUE TITLE
The only messages sent are server start/stop, world and save events

### ISSUE THREAD

**Issue by slikts** [nwesterhausen/valheim-discordconnector#122]
Not sure why, but the player joined/left/died events are not being sent to Discord. I'm running the latest dedicated server version, the plugin version is 1.8.0, the BepInEx version is 5.4.19.0, the toggles are turned on in the config, and the other mods in the server are:
```
Sending CartographySkill version 2.1.1 and minimum version 2.1.1 to the client.
Sending CL&LC version 4.4.13 and minimum version 4.4.13 to the client.
Sending MonsterLabZ CreatureManager version 2.7.0 and minimum version 0.0.0 to the client.
Sending Blacksmithing version 1.1.3 and minimum version 1.1.3 to the client.
Sending Building version 1.2.1 and minimum version 1.2.1 to the client.
Sending Conversion Size & Speed version 1.0.5 and minimum version 1.0.5 to the client.
Sending Cooking version 1.1.4 and minimum version 1.1.4 to the client.
Sending Dual Wield version 1.0.3 and minimum version 0.0.0 to the client.
Sending org.bepinex.plugins.evasion SkillManager version 1.0.1 and minimum version 0.0.0 to the client.
Sending Farming version 2.1.1 and minimum version 2.1.1 to the client.
Sending Stamina Regeneration from Food version 1.5.2 and minimum version 1.5.2 to the client.
Sending InstantEquip version 1.0.3 and minimum version 1.0.2 to the client.
Sending Lumberjacking version 1.0.2 and minimum version 0.0.0 to the client.
Sending Mining version 1.1.2 and minimum version 1.1.2 to the client.
Sending org.bepinex.plugins.packhorse SkillManager version 1.0.1 and minimum version 0.0.0 to the client.
Sending Ranching version 1.1.0 and minimum version 1.1.0 to the client.
Sending Resurrection version 1.0.3 and minimum version 1.0.3 to the client.
Sending Sailing version 1.1.3 and minimum version 1.1.3 to the client.
Sending Sailing Speed version 1.0.1 and minimum version 0.0.0 to the client.
Sending TargetPortal version 1.1.5 and minimum version 1.1.5 to the client.
Sending org.bepinex.plugins.tenacity SkillManager version 1.0.1 and minimum version 0.0.0 to the client.
Sending org.bepinex.plugins.vitality SkillManager version 1.0.1 and minimum version 0.0.0 to the client.
Sending VALKEA version 2.0.2 and minimum version 2.0.2 to the client.
Sending TheBeesDecree.VALKEA ItemManager version 2.0.2 and minimum version 0.0.0 to the client.
```

**Comment by gstrange42** [comment]
I have the same, I have narrowed it down to Epic Loot, It seems some mods that have been updated with Server Sync are causing some messages to be suppressed.

**Comment by nwesterhausen** [comment]
Thanks for investigating. I will have to take a look an what has changed in Valheim, maybe there's a different way the player connections are supposed to be hooked into. All I did this morning was look for a spot where Epic Loot and VDC collide with the RPC Character Info patch I use to detect players joining, and there was no overlap. I will look more into it this evening after work.

**Comment by gstrange42** [comment]
> 

Cheers, I hope you find the problem.

**Comment by gstrange42** [comment]
Also, I have no mods in common with Slikts. I'll try to get a mods list

**Comment by nwesterhausen** [comment]
I believe this issue is same as one in #123, and should be "fixed" in 2.0.0. That version removes code which was trying to cast the steamid of the player from a socket. In the recent versions of Valheim it uses PlayFab for crossplay, and that was breaking the methods I was using. 

Player Join/Leave messages work again. Leaderboard is disabled and using the %STEAMID% variable is also not possible. This is because they all tied into the steamid.

**Comment by gstrange42** [comment]
I'll give it a try later, and let you know if there are any issues.

**Comment by gstrange42** [comment]
Just did a quick test, and player announcements are back.
