### ISSUE TITLE
no "Player leave" notification od Discord

### ISSUE THREAD

**Issue by Juraszka** [nwesterhausen/valheim-discordconnector#128]
There is no information about player left from server by logout.
When kicked, notification is present.

**Comment by nwesterhausen** [comment]
What version of discord connector are you using? What other mods are you using?

**Comment by nwesterhausen** [comment]
Is there any error message in the log when the player leaves ?

**Comment by Juraszka** [comment]
nowy 1.txt
Kto ma dostęp
Nieudostępniony
Właściwości systemowe
Typ elementu
Tekst
Rozmiar
737 bajtów
Zajęte miejsce
737 bajtów
Lokalizacja
VALHEIM
Właściciel
ja
Zmodyfikowano
22:48 przeze mnie
Otwarty
22:49 przeze mnie
Utworzono
22:48 w aplikacji Google Drive Web (Unverified)
Dodaj opis
Przeglądający mogą pobierać
11/07/2022 22:47:28: PlayFab network error in session 'wincls-valheim' and network 2e4a179c-cfe5-43f4-8ee4-9dacd055de8a|AwAuaHWp/mPWVm0C2keqUorieWEOVFdlc3RFdXJvcGUAAAAAAAAAAAAAUXZkEL9Xa34rfnIgJk1n6olEkKykili28X3MawG4mvIpb0pkbnM4MWU1LTkyNTdkZWYxLWM1MTctNDkyZC1hZDNkLTE1Y2RjMjQ2Zjg1ZS53ZXN0ZXVyb3BlLmNsb3VkYXBwLmF6dXJlLmNvbQ==: the operation was called with an invalid handle
the operation was called with an invalid handle
11/07/2022 22:47:28: Failed to send, suspend TX on playfab/32D20C9BB52FA743 while trying to reconnect
Failed to send session data. Error: /Event/WriteTelemetryEvents: The requesting entity is not authorized to write events with namespace playfab.party. Allowed namespaces can be 'custom' or begin with 'custom.'.

**Comment by nwesterhausen** [comment]
DiscordConnector doesn't do anything with PlayFab.party or anything like that besides looking up the socket hostname, which is a read and not write error. Based on the log snipped you posted, I think it's most likely that some other mod is causing an error when the player is leaving; and that mod isn't doing anything when players are kicked. Could it be something with server-side characters and server sync stuff?

When you added 2.0.2, did you update any other mods?

**Comment by Juraszka** [comment]
I never saw leave notification.
Propably problem witch ServerCharacters or AzuAntiCheat - these mods use Discord info too.

**Comment by Juraszka** [comment]
I checked and without ServerCharacters or AzuAntiCheat, notification about player leave is present but if one of there mods are, this info gone. No matter what mod - there is no information about Player leave on ServerCharacters and/or AzuAntiCheat.
If it will be problem with one of these mods i will ask author for checking compatibility with DiscordConnector but in these case - when with any of these mods, the problem is present, I would like to ask you for checking what is problem because DiscordConnector isn't compatible with two very nice server-side mods
