### ISSUE TITLE
More Options for Messages

### ISSUE THREAD

**Issue by nwesterhausen** [nwesterhausen/valheim-discordconnector#135]
1. would be nice to customize the POS information sent with the messages
2. want more variables dynamically created from the server details (e.g. name)

**Comment by nwesterhausen** [comment]
Here is a build of 2.0.4 which includes a configuration in the variables config file for modifying the POS format and also modifying the `Coords: (%POS%)` message which gets included by default when no `%POS%` is in the message config for that message but position sending is on.

[DiscordConnector.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10058038/DiscordConnector.zip)

**Comment by BaldrAdmin** [comment]
Thanks! We'll load this up and give it a go!

**Comment by BrisWackyAdventures** [comment]
Is there a % % prompt, that when a player dies, it posts the cause of death? ie Player Death Message = %PLAYER_NAME% was killed by a %CREATURE_NAME% (ie Boar/Neck/Fuling Shaman etc) ) and Player Death Message = %PLAYER_NAME% took damage from %STATUS% (ie Drowning/Fire/Smoke/Fall Damage etc)

**Comment by nwesterhausen** [comment]
No there isn't. I can't get that info without also being on the client side. There's a mod that does just death messages and sends to discord called Darwin awards
