### ISSUE TITLE
after 2.1.0 update webhook doesn't seem to work.

### ISSUE THREAD

**Issue by StellarwhimsRepo** [nwesterhausen/valheim-discordconnector#143]
config files got moved to the new folder as described, however the webhook does not seem to be working for shouts or events.

I also saw this in my server log - https://pastebin.com/wWGdwf4H

**Comment by nwesterhausen** [comment]
Thanks. I did not notice because building it on my machine still had pieces from previous builds. 

Basically the newtonsoft dependency was not packaged with the mod, which meant anything with JSON did not work (sending things to webhook). Fixed in 2.1.1

**Comment by StellarwhimsRepo** [comment]
whoopsie! thanks for fixing!
