### ISSUE TITLE
feature request - filter messages

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#17]
I was going through the change-log looking for it, but didn't read anywhere that filtering messages was available. That would be the main reason for us to switch out what we are currently using. This one we have is supposed to, but is failing.

We have zones and sleep mods shouting into our discord where we don't want to see them, so if you could add a configurable filter to apply before messages are sent, that would be awesome!

If this is already a current feature, please let us know =]

**Comment by nwesterhausen** [comment]
Can you give me some more information? Like what mods they are, and the messages they are generating? I assume you are using the valheim-discord-notifier mod to send messages currently.

**Comment by CruxCraft** [comment]
> Can you give me some more information? Like what mods they are, and the messages they are generating? I assume you are using the valheim-discord-notifier mod to send messages currently.

Correct, though we went ahead and made the switch now. The two mods (currently) sending messages to chat are
World of Valheim - SSC - V0.7.2-892-0-7-2-1632506303
R1NS3-SkipSleep-1.0.5
They send shouts to the server with a prefix or predictable format, that if given the opportunity to filter out entire messages based on defined string or regex, then it be able to block any plugin that uses predictable prefixes/strings (WoV or SkipSleep)

**Comment by CruxCraft** [comment]
just another observation, there seems to be less logged by BepInEx than valheim-discord-notifier. It's kind of nice to be able to look back at our archived logs when needed. Could look to see when messages are being sent or muted etc... We like logs lol. Maybe an option in the config as I realize not everyone enjoys extra bits in the logs?

**Comment by nwesterhausen** [comment]
I like logs too. It should be an easy thing to add some (config opt-in) logging for this mod.
