### ISSUE TITLE
2.1.9 blank second webhook default settings causes cronjob shout chat command to spam discord.

### ISSUE THREAD

**Issue by StellarwhimsRepo** [nwesterhausen/valheim-discordconnector#176]
if you leave the second webhook blank because you don't use it, and use cronjob it spams discord with default settings.

setting up the second webhook and setting it to only show playerFirstJoin messages makes things much quieter.

cron job example entry for repro - 

  - command: s A faint rumble in the distance ... resources reset every 3 days!!
    schedule: 15 9 */3 * *

**Comment by nwesterhausen** [comment]
Thank you. Will be working on a fix later today

**Comment by StellarwhimsRepo** [comment]
> Thank you. Will be working on a fix later today

i forgot you were pretty much github only for support so it took me a bit to remember how to report the bug. thanks for responding quick!

**Comment by StellarwhimsRepo** [comment]
it could be related to your setting to send shout chat from non players. idk. wanted to throw that thought at you in case it helps.

**Comment by nwesterhausen** [comment]
Thanks. I will look at that too

**Comment by nwesterhausen** [comment]
Fixed in release 2.1.10 should be published shortly on Thunderstore or from release here https://github.com/nwesterhausen/valheim-discordconnector/releases/tag/v2.1.10
