### ISSUE TITLE
Chat Shout | Potential Issue

### ISSUE THREAD

**Issue by ValhallaCommunity** [nwesterhausen/valheim-discordconnector#193]
Hey Nwest!

Hope all is going good!

I noticed in the recent update 2.1.11 that our chat shout messages are no longer appearing in our discord channel.

This is enabled:

```
## If enabled, this will send a message to Discord when a player shouts on the server.
# Setting type: Boolean
# Default value: true
Chat Shout Messages Notifications = true
```

Thanks for taking a peak!

**Comment by nwesterhausen** [comment]
I'm not sure why this would be happening, to get some clue I would need to get some debug-level logs from the server when people are shouting to see what DiscordConnector reports is happening. When it encounters a shout it should be trying to send it, and that would be visible. If it discards the shout, it also reports that.

**Comment by ValhallaCommunity** [comment]
next server patch update (next 1-2 days), I'll test with debug level and attempt to shout in game

**Comment by ValhallaCommunity** [comment]
I turned on all these settings

![image](https://user-images.githubusercontent.com/124803112/228708193-d07f9840-8404-4f1a-a34c-fe4280e4acd1.png)

Do you want the records-log.db file? We're not getting shouts in the server messages, but we've been testing for few hours, nothing came up in client and server log.

**Comment by nwesterhausen** [comment]
Sorry for the confusion. You can keep those off. You need to change BepInEx to log at the Debug level for the logs to show up. That's in the BepInEx/Config/BepInEx.cfg file. There's a log level setting you need to append debug to the list of logs. 

Only the server needs to do this. The clients will not have anything pertaining to Discord Connector.

As an aside, it's on my list of things to add is better ways to enable debug logging for just Discord Connector..

**Comment by ValhallaCommunity** [comment]
I debated about flipping that on, next patch (in the next 1-2 days; I'll flip those configs and test)! Thanks for the clarity!

**Comment by nwesterhausen** [comment]
Shouts are not working as reported by a few others. I need to do some more testing to confirm they work as expected with the newer updates to Valheim.

**Comment by nwesterhausen** [comment]
I have verified shouts are working on a dedicated server with only Discord Connector loaded.

I also have added a config option to the main config file "Log Debug Messages" which will log debug messages to the info channel, allowing them to be easier to see. Set it to true, and then see if there are hints to why your chats are not being sent.

This setting isn't in the live version yet but here is a build with it (attached): 
[DiscordConnectorLogDebugSetting.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/11373141/DiscordConnectorLogDebugSetting.zip)

**Comment by nwesterhausen** [comment]
Found that there's a conflict with KG Server Control 6.0.0

KG Said they will fix the issue in the next version.

**Comment by ValhallaCommunity** [comment]
Yep can confirm after removing server control 6.0.0 thanks for following up Nwester!!
