### ISSUE TITLE
On death, it announced me joining the world twice

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#20]
I just died, and it announced me joining the world when the loading screen first came up, and then again when it went away

**Comment by nwesterhausen** [comment]
Did you roll back to 0.7.0 or 0.6.0?

**Comment by CruxCraft** [comment]
> Did you roll back to 0.7.0 or 0.6.0?

I rolled back to 0.6.0 now... & a player is on who dies a lot, so I should be able to tell you soon if it only started with 0.7.0

**Comment by nwesterhausen** [comment]
So I used the wrong comparison... was guaranteed to find non-matches and stop instead of matching and stopping

**Comment by nwesterhausen** [comment]
I think the only thing not fixed at the moment is two join messages when one should be a death message -- but I have to figure out a way to tell. Might have to record the player joining the first time then if they did, send a death message. I don't think they can disconnect without the server noticing. Going to try that now actually

**Comment by CruxCraft** [comment]
> I think the only thing not fixed at the moment is two join messages when one should be a death message -- but I have to figure out a way to tell. Might have to record the player joining the first time then if they did, send a death message. I don't think they can disconnect without the server noticing. Going to try that now actually

If you ever need a 2nd person to jump in for some sort of testing, I'm available often for the time being and during random hours.

z.#8068

**Comment by CruxCraft** [comment]
> Death messages are added in 0.8.0, at least in my testing of my client to my server.

I was wondering what in the world lol... went to download 0.7.1 from Nexus instead of here to Endorse it, and then saw 0.7.2 and 0.8.0

That sounds awesome because that is the only thing Notifier still had so I should be able to remove the it if this works =]
Doing that now...

**Comment by CruxCraft** [comment]
It is now only a single join message instead of two... 

is the join message intentional? As the player didnt actually leave the world... or it is something that has to be circumvented because it goes back to the loading screen in-between death/respawn

if it has to be circumvented due to the loading screen, maybe when a player dies it adds to a counter, then when respawning if that counter is 1, it is reset and there isn't a join message? I don't know what it looks like on your end & my abilities are worse than rusty

**Comment by CruxCraft** [comment]
I will check & test death messages specifically before noon (2-3pm)

**Comment by CruxCraft** [comment]
Appears fixed on the test server =] Thanks
