### ISSUE TITLE
More specific death messages

### ISSUE THREAD

**Issue by sinoth** [nwesterhausen/valheim-discordconnector#200]
Would it be possible to give more specific death messages?

Similar to this mod:
https://valheim.thunderstore.io/package/Valkyrie_Mods/Valkyrie_Death_Messages/

Extra humiliation if the server can see you died from a tree...

**Comment by nwesterhausen** [comment]
You could use that mod with Discord Connector and it could send the shouts to your Discord (if it does shout, looked like it did from the screenshot). 

Since Discord Connector is only on the server, it doesn't know what happens to the players, so this type of feature isn't possible.
