### ISSUE TITLE
Server Start/Stop notifications when player leaves or joins 

### ISSUE THREAD

**Issue by justinglavin** [nwesterhausen/valheim-discordconnector#207]
I have been receiving "Server is starting up" notifications when a player joins, and "Server is stopping" and "Server has stopped" notifications when a player leaves. The server is staying up this entire time.

Not sure what changed as everything was working fine for weeks. 

I have disabled the start/stop notifications in the config files, and they are not triggering during the actual server startup/shutdown. But they are still triggering when a player is leaving or joining the server.

![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/13800152/dd0b53da-d47c-4cae-a804-cd2ec6a430b3)

Installed Mods: https://valheim.thunderstore.io/package/LordJay/Auto_Feed/
https://valheim.thunderstore.io/package/ishid4/BetterArchery/
https://valheim.thunderstore.io/package/Marlthon/Cats/
https://valheim.thunderstore.io/package/sbtoonz/Craft_From_Containers_Redux/
https://valheim.thunderstore.io/package/nwesterhausen/DiscordConnector/
https://valheim.thunderstore.io/package/RandyKnapp/EpicLoot/
https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots/
https://valheim.thunderstore.io/package/makail/ItemDrawers/
https://valheim.thunderstore.io/package/posixone/NoMovementPenalty/
https://valheim.thunderstore.io/package/Advize/PlantEasily/
https://valheim.thunderstore.io/package/Advize/PlantEverything/
https://valheim.thunderstore.io/package/TastyChickenLegs/RecyclePlus/
https://valheim.thunderstore.io/package/OdinPlus/TeleportEverything/
https://valheim.thunderstore.io/package/MidnightMods/ValheimArmory/
https://valheim.thunderstore.io/package/dannypacquiao/Valweed/

Most recently installed mod (around the time this issue started occurring): https://valheim.thunderstore.io/package/Marlthon/Cats/

**Comment by justinglavin** [comment]
This was user error. I realized my server configuration was copying the discord connector config to the client machines

**Comment by nwesterhausen** [comment]
I was going to ask about that. Glad you got it figured out!
