### ISSUE TITLE
[BUG] TWO IPs displaying with webhook on discord instead of ONE

### ISSUE THREAD

**Issue by J0HNN1E** [nwesterhausen/valheim-discordconnector#221]
Hello,

**Describe the issue**
With the discord webhook of server starting, on the first restart it says the right IP (in my case, 141.94.99.153 with "Server starting on %PUBLICIP%". After a shutdown and another restart, it says now: "Server is starting on 93.23.197.125..." but it's a bad IP which doesn't works btw.. I don't know why it does it. Btw, when you do another restart, it says back the right IP (141.99..) and after another restart, it says the wrong... etc.. 1 on 2 times the IP displayed is GOOD. 1 on 2 times the IP displayed is WRONG.

**Server Environment**
Dedicated machine (server) at OVH (France)
OS: Ubuntu Server 22.04 LTS
Specs: AMD Ryzen 5 5600X 3.6Ghz | 64Go RAM DDR4 2666Mhz | 1gbps professionnal fiber bandwidth

**Installed Mods**
AdventureBackpacks 1.6.26
AllTameable-Overhaul 1.3.1
AlweStats 6.0.5
Armory 1.0.7
AzuAntiCheat 4.3.0
AzuDevMod 1.0.3
AzuExtendedPlayerInventory 1.2.2
AzuWorkbenchTweaks 1.0.1
Backpacks 1.2.6
BalrondFurniture 1.0.1
BalrondShipyard 1.2.2
BetterNetworking 2.3.1
Blacksmithing 1.2.4
BlacksmithTools 2.0.1
BoatAdditions 1.1.5
BossDespawn 1.1.0
Building 1.2.4
BuildIt 1.6.3
BuildPieces 1.3.3
ChangelogEditor 1.0.4
ChaosArmor 12.3.1
Clutter 0.1.5
ColoredTrollArmors 0.1.0
ComfyGizmo 1.8.0
Compass 1.3.0
ConfigurationManager 18.0.1
Cooking 1.1.14
CookingAdditions 1.0.2
CraftingFilter 0.8.0
CreatureLevel&LootControl 4.5.12
CronJob 1.5
CW_Jesse'sValheimFramerateBooster 1.1.2
DamageOverlay 1.0.1
DestroyCartAndBoat 1.0.0
Digitalroot'sSlopeCombatAssistance 2.0.17
DigitalrootBetterClubs 1.1.30
DigitalrootChainManager 1.0.5
DisplayBepInExInfoIn-Game 2.0.1
DropThat! 2.3.9
EpicMMONotifier 1.0.3
EpicMMOSystem 1.7.8
ExpandWorldData 1.8
ExpandWorldSize 1.11
Exploration 1.0.1
Farming 2.1.9
FastLink 1.3.9
FineWoodPieces 1.1.2
FirstPersonMode 1.2.3
FishChum 0.0.6
FollowDistance 1.0.0
Foraging 1.0.5
Frogger.CosmeticSlots 1.2.0
GapFiller 1.0.3
GBCustomTable 0.1.1
goldbees 1.0.0
Groups 1.2.0
Guilds 1.0.1
HappyHour 0.1.0
HeightmapUnlimited 1.4.0
Herbalist 1.2.5
HildersCloths 1.0.0
HildirsQuest 1.0.1
IKnowThings 1.0.0
ImFRIENDLYDAMMIT 1.1.1
InfinityHammer 1.39
InstancedVillages 0.0.4
Jewelcrafting 1.4.20
Jotunn 2.12.7
kg.MarketplaceNpcModels 1.0.0
Leash 1.0.6
LegendaryWeapons 1.0.1
LessZDOCorruption 1.0.0
LinenCapeColors 0.1.2
LocalizationCache 0.2.0
Lumberjacking 1.0.4
MagicalMounts 1.5.9
MagicPlugin 1.6.1
MagicWeapons 1.1.1
MarketplaceAndServerNPCs 9.0.14
Mining 1.1.4
Monstrum 1.2.1
MonstrumAshlands 1.0.0
MonstrumDeepNorth 1.0.0
MultiplayerTweaks 0.5.0
NoAFKEvents 1.0.2
OdinArchitect 1.2.7
OdinCampsite 1.5.2
OdinShipPlus 0.3.3
OdinsHollow 1.1.6
OdinsKingdom 1.1.21
OdinTrainingPlace 1.5.2
PerPlayerDifficulty 1.0.1
Pinnacle 1.4.1
PlantThings 1.0.0
PotionsPlus 4.1.11
PotteryBarn 1.10.0
Professions 1.4.0
Pwks_Boats 0.0.2
Pwks_Creatures 0.0.1
Pwks_Weapons 0.0.3
Ranching 1.1.2
Recycle_N_Reclaim 1.1.8
RenderLimits 1.8
RepairStation 1.0.3
ResourceUnloadOptimizer 1.0.1
RRRCore 3.1.2
RtDBiomes 1.2.7
RtDOcean 1.2.4
Sailing 1.1.6
Scythes 1.0.3
SeaAnimals 0.2.0
SearsCatalog 1.3.0
ServerCharacters 1.4.9
ServerDevcommands 1.60
Skyheim 1.3.4
SlayerSkills 1.0.4
SNEAKer 1.0.9
Soulcatcher 4.5.2
SouthsilArmor 2.7.3
SpawnerTweaks 1.21
SpawnThat! 1.2.7
Starvation 1.0.2
Stronghold 0.0.8
StructureTweaks 1.23
TargetPortal 1.1.10
TerminalChecker 1.0.0
UpgradeWorld 1.42
ValheimCrossServerPortals 0.1.0.0
ValheimDiscordConnector 2.1.14
ValheimHitmarker 1.2.2.1
VALKEA 2.1.7
VNEI 0.12.0
WackysDatabase 2.0.6
WackySpawners 1.0.3
WardIsLove 3.2.2
Warfare 1.5.0
WarfareFireAndIce 1.0.1
WeaponHolsterOverhaul 1.0.7
Weedheim 1.0.6
WieldEquipmentWhileSwimming 1.0.1
WorldAdvancementProgression 0.1.4
WorldEditCommands 1.43
XRayVision 2.1.6

**Additional context**
It happens only 1 on 2 times. Weird lol, but there isnt a second webhook installed (I tryed with each solution btw with only 1 webhook and with 2 webhooks (primary & secondary)

Thanks for your work!! I love it btw! :D
![discord0](https://github.com/nwesterhausen/valheim-discordconnector/assets/76440328/c1f650af-fec6-4644-8c8b-82c2364e0d1c)
![discord1](https://github.com/nwesterhausen/valheim-discordconnector/assets/76440328/752178f1-5c7e-424f-b6f5-5dfc4df8d953)
![cfg](https://github.com/nwesterhausen/valheim-discordconnector/assets/76440328/d6d0a519-b394-49a4-9602-6e1e1caec1e5)

**Comment by nwesterhausen** [comment]
As it is right now, the public IP is grabbed from some method inside the Valheim server. So it seems like that is _wildly_ inconsistent if 50% of the time it has the wrong IP address! 

I think an option to fix can be defining a custom IP lookup function and using that instead.

**Comment by nwesterhausen** [comment]
Going forward, discord connector finds its own value for the public IP using https://ifconfig.me/ip when the server starts. This value is cached until the server restarts.
