### ISSUE TITLE
[BUG] looks like thunderstore kicked the mod - maybe a re-upload would be enough?

### ISSUE THREAD

**Issue by himpich** [nwesterhausen/valheim-discordconnector#239]
**Describe the issue**
[Describe what isn't working the way you expect it to.]

https://valheim.thunderstore.io/package/nwesterhausen/DiscordConnector/ is dead

**Expected behavior**
https://valheim.thunderstore.io/package/nwesterhausen/DiscordConnector/ should contain the mod

**Additional context**
Some time ago they had problems at thunderstore and removed some mods (malware detection?) - they fixed it but maybe they (the files) need to be uploaded again?

**Comment by nwesterhausen** [comment]
Thanks for posting the issue. I had to reach out to them beck when they updated there detection stuff a few weeks ago. 

I just reached out and it was very quick for them to fix it. It shows up for me now.

**Comment by himpich** [comment]
Website is back, still waiting for the searchindex (thunderstore mod manager / r2modman) to show it.

Thanks :)

**Comment by himpich** [comment]
There it is
