### ISSUE TITLE
Feature Request - multiple webhooks

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#24]
The ability to have webhook1, webhook2, webhook3 etc, & then be able to choose which webhook(s) the messages are sent to

**Comment by CruxCraft** [comment]
If this gets added, I am interested in having the option for all players POS to be polled every 300 seconds or something and then send that to the webhook of my choice, but I can add the request after this one =]

**Comment by nwesterhausen** [comment]
Multiple webhooks gets really complicated if you want to be able to customize all of them. Not sure how to really tackle this.

Might have to abstract the message sending to a webhook controller which can set up a message for each webhook as needed for every event

**Comment by CruxCraft** [comment]
yeah... I was hoping it'd be easy to add something like

Webhooks = https://URL.one;https://URL.two

but I don't know how any of that is handled with this. I really should read through the source code more to get a better understanding, even if I don't know cs

I do have some ideas on simplifying the configs in general though... I might send you a copy later to see what you think

**Comment by nwesterhausen** [comment]
Multiple webhooks can work this way:

```
Webhook1Url=https://...
Webhook2Url=https://...
Webhook3Url=https://...

ContentForWebhook1=ServerStart,ServerStop,Join,Leave,Death,Ping,Shout
ContentForWebhook2=ServerStart,ServerStop,GameSaved
ContentForWebhook3=All
```

Then it can be determined what to send where when dispatching the content to discord.

**Comment by nwesterhausen** [comment]
2 webhooks are supported with 2.1.9 in PR #170
