### ISSUE TITLE
[BUG] no messages to discord channel (System.Net.WebException: Error: NameResolutionFailure)

### ISSUE THREAD

**Issue by rshingleton** [nwesterhausen/valheim-discordconnector#247]
**Describe the issue**

- Webhook setup with LinuxLGSM AlertManager, works as expected
- Plugin installed and configured
- Webhook setup with discord connector plugin

**Expected behavior**
No messages are being received by Discord. Seeing random NameResolutionFailure which appear to be in association with the connector.

**Configuration**
Upload the `config-dump.json` file from the Discord Connector config folder.

[config-dump.json](https://github.com/nwesterhausen/valheim-discordconnector/files/14440913/config-dump.json)

**Server Environment**
hosted Ubuntu 22.04 on KVM 

**Installed Mods**
ValheimPlus [0.9.12.0]

**Additional context**
[Info   :Valheim Discord Connector] Unable to get World Name from ZNet. Object reference not set to an instance of an object
[Info   : Unity Log] 02/28/2024 04:30:41: Exception while waiting for respons from https://checkip.amazonaws.com/ -> System.Net.WebException: Error: NameResolutionFailure
  at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00044] in <32fc020d7373456995b3d44fa885e01a>:0 
  at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <32fc020d7373456995b3d44fa885e01a>:0 
  at System.Net.WebOperation.Run () [0x0009a] in <32fc020d7373456995b3d44fa885e01a>:0 
  at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <32fc020d7373456995b3d44fa885e01a>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <32fc020d7373456995b3d44fa885e01a>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <32fc020d7373456995b3d44fa885e01a>:0 
  at ZNet.<GetPublicIP>g__DownloadString|10_0 (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <7cee6523c63d411194457bfee931d2ed>:0 

[Error  : Unity Log] 02/28/2024 04:30:41: Specified argument was out of the range of valid values.
Parameter name: i

[Info   :Valheim Discord Connector] Trying webhook with payload: {"content":"Server is starting up."} (event: ServerLaunch)
[Info   :Valheim Discord Connector] Webhook has 'ALL' enabled
[Info   :Valheim Discord Connector] Sending ServerLaunch message to Primary Webhook

[LogOutput.log](https://github.com/nwesterhausen/valheim-discordconnector/files/14440915/LogOutput.log)

**Comment by nwesterhausen** [comment]
The ip checking requests in your log which are failing is a function from the game itself, Discord Connector just calls the existing function. With that said, the fact that those are failing name resolution would indicate to me that the message sends to discord also are having the same resolution error and not sending because of that. 

Is it possible for you to ssh into the server and do some `dig discord.com` or an `nslookup discord.com` to see if it returns an IP address or not?

**Comment by rshingleton** [comment]
DNS Seems to be functionally working as expected. I suspected some wierd ipv6 issue or firewall issue so I went through and attempted to disable ipv6 settings and disabled the firewall (ufw and iptables) for some testing but it made no difference at all. I'm honestly at a loss as to why this is not working, as I said, I have the same hook in my LGSM configs for the alert manager and it does work. If I kill the server and let it auto-restart (via crontab), I get notifications in the discord channel.

> dig discord.com

; <<>> DiG 9.18.18-0ubuntu0.22.04.2-Ubuntu <<>> discord.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46437
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;discord.com.			IN	A

;; ANSWER SECTION:
discord.com.		300	IN	A	162.159.136.232
discord.com.		300	IN	A	162.159.137.232
discord.com.		300	IN	A	162.159.138.232
discord.com.		300	IN	A	162.159.135.232
discord.com.		300	IN	A	162.159.128.233

;; Query time: 23 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Thu Feb 29 13:04:27 EST 2024
;; MSG SIZE  rcvd: 120

___________________

> nslookup discord.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	discord.com
Address: 162.159.136.232
Name:	discord.com
Address: 162.159.137.232
Name:	discord.com
Address: 162.159.138.232
Name:	discord.com
Address: 162.159.135.232
Name:	discord.com
Address: 162.159.128.233

**Comment by nwesterhausen** [comment]
I'm not sure how to help us get this working. You can turn on the `debugHtppRequestResponses` Toggle to get more logging from the attempted Discord message posting. However, with even the Valheim provided "get public IP" method failing I'm not sure we'll get any more information except that it can't DNS to resolve, since that looks like the errors for the public IP methods. 

In your log I also noticed that ValheimPlus fails to download the config file because of the same `NameResolutionError`, so something isn't working right for the server.
