### ISSUE TITLE
Quality of Life Suggestion - split into two CFG files

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#25]
I might be an outlier here, so if you think differently I understand completely...

having gone up and down that config multiple times and it seeming longer every-time I open it, instead of separating [Notification Content Settings] and [Notification Settings], it might be easier to either combine the related configs, OR (my preference) have a second CFG file for the messages/content settings

**Comment by nwesterhausen** [comment]
I'll think on it. I do think the config has gotten rather large, but what I have seen of best practices is to keep the config in the one file by plugin id.

Maybe there are some settings that can be combined.

**Comment by nwesterhausen** [comment]
After some more thought, using multiple config files sounds like it would be a good idea, and they can simply be {{plugin-id}}-messages.cfg, {{plugin-id}}-settings.cfg and whatever else.

**Comment by nwesterhausen** [comment]
This change is merged into dev and passed testing/validation.
