### ISSUE TITLE
Multiple servers/world name

### ISSUE THREAD

**Issue by TheOzarkWizard** [nwesterhausen/valheim-discordconnector#254]
I am currently running 2 dedicated servers on the same PC with 2 different instance ids. Currently, the messages sent to discord only say "the server", regardless of which server or world it is being sent from.

I currently am using no-ip hostnames and port numbers to connect to the different servers on the same machine, as I do not wish to share my public IP. I would very much appreciate it if another argument could be added, similar to the  %PUBLICIP% argument, for example %SERVER_NAME% or %WORLD_NAME%, that would display what world or server the message is coming from.

Previously, I used a program called Valheim Server Warden. I loved this program, and it has the described functionality (similar, at least), however it is long defunct. (last updated Feb 8, 2023.) https://github.com/Razzmatazzz/ValheimServerWarden

Valheim Server Warden and Valheim save shield are no longer needed, as the instance ID argument and backup functions have been added to the core game. Discord webhooks were broken when crossplay was added, and i missed the feature so badly that I have sought out discordconnector. some example messages of what I would like to see are:

%SERVER_NAME% or %WORLD_NAME% has started
Floki has died in %SERVER_NAME% or %WORLD_NAME%

This way, if one of my friends is playing on server 2, and they see that I have died on server 1, they might be able to come help or defend the base without me having to go get them. There are more reasons I would need this functionality, but this is the simplest example.

**Comment by nwesterhausen** [comment]
Do the servers share the same configuration? DiscordConnector has a set of 10 custom variables that could be used to hold the world name or similar. %VAR0% - %VAR9%. You could set %VAR0% to be the world name in the config for each different server, then set up the messages to include that variable in the messages.

I try to do maintenance updates on discord connector but I haven't made many big changes in a while. I am not sure that there is a way to access the world name.. I just took a brief look at the ValheimServerWarden repo you linked and that looks like it took the world name as part of the configuration. So I will mark this as a feature request, and when I get back to this project I can dig in and see what is available to pull in for a variable like SERVER_NAME or WORLD_NAME.

**Comment by nwesterhausen** [comment]
Digging into the existing code I found that the `%WORLD_NAME%` variable was already there and functional, just not documented.
