### ISSUE TITLE
Add option to display current player count with player join/leave message

### ISSUE THREAD

**Issue by hardtimes** [nwesterhausen/valheim-discordconnector#258]
Currently I believe the only way to see the current player count is to wait for the scheduled message.  To me, it would be more useful to see that count with the join/leave message. 

So when it says "Player X has joined" it could optionally say.

"Player X has joined.
Total players on server: N"

or 

"Player X has left the server.
Total players on server: N"

Since when a player joins or leaves is the only time one would expect player counts to change outside of a crash or restart.

An even more versatile approach would be to have all data points available in variables so we can fully customize our own messages with this information as desired.

**Comment by nwesterhausen** [comment]
available in 2.2.2

**Comment by hardtimes** [comment]
Fantastic, thank you!
