### ISSUE TITLE
Variable timestamp

### ISSUE THREAD

**Issue by MrHatter89** [nwesterhausen/valheim-discordconnector#272]
Is it possible to add a system event time variable in the form of a Unix timestamp?
So that we can add timestamps to notifications in discord in the form "`<t:1717406662>: %PLAYER_NAME% left the server.`"

_This screenshot is an example from another game._
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/2678831/7364a6f7-7b1e-4ee1-9eb6-72c5e5eb2784)

In the current implementation, connection time is difficult to see, especially when viewed through a mobile phone.
![Screenshot_1](https://github.com/nwesterhausen/valheim-discordconnector/assets/2678831/7f4f74fd-d63a-4e2a-a46c-451f743c9627)

**Comment by nwesterhausen** [comment]
In the next release:

- Added a few new variables related to timestamps and time
  - `%TIMESTAMP%` - replaced with `<t:UNIX_TIMESTAMP>` which Discord will convert to the user's local time
  - `%TIMESINCE%` - replaced with `<t:UNIX_TIMESTAMP:R>` which Discord will convert to a relative time (e.g. 2 hours ago)
  - `%UNIX_TIMESTAMP%` - replaced with the UNIX timestamp of the event (e.g. 1634567890). This can be used to create a custom timestamp format in the message.
