### ISSUE TITLE
Option to have different webhook for each message

### ISSUE THREAD

**Issue by vavavr00m** [nwesterhausen/valheim-discordconnector#273]
**Is your feature request related to a problem? Please describe.**
Certain messages could get easily lost.

**Describe the solution you'd like**
I would like an option to have separate webhooks for the notifications. For example, I have a channel for the server info where I'd like the Server Join Code and Server IP/Port to go to as well as separate channel for each type - server logs (start, stop, join, leave), messages, leaderboards.

**Describe alternatives you've considered**
None.

**Comment by nwesterhausen** [comment]
Currently Discord Connector supports two webhooks which can be customized to only display messages of specific types. 

See the "Secondary Webhook URL" option in [main config](https://discord-connector.valheim.games.nwest.one/config/main.html) and the [Webhook Event Definitions](https://discord-connector.valheim.games.nwest.one/config/webhook.events.html)

I would consider a solution as you want to be more webhooks to use?
