### ISSUE TITLE
Allow math with variables

### ISSUE THREAD

**Issue by hardtimes** [nwesterhausen/valheim-discordconnector#275]
Thanks to the new variable for number of players, It can be reported, which is wonderful.  However sometimes the player count doesn't update until after an event.  Like a player logoff.  In the following message, player count should be 0.  If I could account for this using basic math, then I could could change the message to include "Number of players is now: (%NUM_PLAYERS% - 1)".  

Actual message: "Grim has left to play fruit ninja because they aren't a real Viking. Number of players is now: 1"

**Comment by nwesterhausen** [comment]
I wonder if the math is always off on leaving, and we can just have Discord Connector automatically display NUM-1 if the message being sent is a leave message?

**Comment by nwesterhausen** [comment]
Set this up to specifically subtract 1 from the number of online players when the event occurring is a player leaving:

![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/2317381/d812415f-3a1d-4658-9b82-854a16222928)

**Comment by hardtimes** [comment]
Once again, excellent work!  Thank you!
