### ISSUE TITLE
[BUG] If %VAR1% is used, the variable names are printed out instead of the values

### ISSUE THREAD

**Issue by vavavr00m** [nwesterhausen/valheim-discordconnector#276]
**Describe the issue**
Under Server messages, this was used `Server has started! %VAR1%` and %VAR1% has `@Valheim %WORLD_NAME% IP/Port: %PUBLIC_IP%:2457 | Join Code: %JOIN_CODE%` the variables, except for %PUBLIC_IP%, work if they are in messages but if they're in %VAR1%, and possibly any allowable VAR #, the variable names get literally printed out. I was using `Server is started. %VAR1%` where %VAR1% contains `@here %PUBLICIP%:2457` before the 2.2.2 update and it worked out just fine.

**Expected behavior**

1. Variables inside the variable %VAR1% will be displayed.
2. %PUBLIC_IP%:[port] value must be displayed whether inside %VAR1% or in the messages instead of the variable name

**Screenshots**
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/4675132/f113c762-1c07-4a9d-bd06-084176909fd3)

**Server Environment**
Where are you running the Valheim dedicated server? Home dedicated server running on Windows 11?

**Comment by nwesterhausen** [comment]
Right now variable replacement is not recursive. Should be easy to make the custom %VARN% variables be evaluated first, then do any other replacements.

**Comment by nwesterhausen** [comment]
It's a change in the code. 

We just need to change the order that messages are transformed in the MessageTransformer code. I think right now, the dynamic variables are changed out first, then the VARN variables. We just need to reverse it.

**Comment by nwesterhausen** [comment]
No problem. I'll work on this to get something released this week!

**Comment by nwesterhausen** [comment]
This is in release 2.3.0
