### ISSUE TITLE
[BUG] Mod Not Available

### ISSUE THREAD

**Issue by silasclockwork** [nwesterhausen/valheim-discordconnector#314]
I am directed to Thunderstore to find this mod, and the version 2.3.2 that is supposed to work with Bog Witch isn't there. I can't find it anywhere. I would really like to try this mod, but there doesn't even seem to be a way to do so.

**Comment by nwesterhausen** [comment]
hadn't released it yet, the old version probably does work with bog witch for what its worth.

I'll go ahead and release the 2.3.2 right now -- was previously waiting on a different issue before doing so and forgot to move forward to upload it

**Comment by nwesterhausen** [comment]
It's released now [tstore link](https://thunderstore.io/c/valheim/p/nwesterhausen/DiscordConnector/versions/)
