### ISSUE TITLE
Incorrect setting

### ISSUE THREAD

**Issue by DarkKostas** [nwesterhausen/valheim-discordconnector#48]
https://github.com/nwesterhausen/valheim-discordconnector/blob/9cbc7190efa82b6d0c04454dcc289f40e7809931/src/Config/TogglesConfig.cs#L243

This and "stop" should have their own value i guess. Cause now they don't seem to do any change independently

**Comment by nwesterhausen** [comment]
You're right, that's definitely a typo. I will get it fixed
