### ISSUE TITLE
Feature Request: Leaderboard top 5

### ISSUE THREAD

**Issue by thedefside** [nwesterhausen/valheim-discordconnector#58]
I know you are working on updating the leaderboard, so I thought I would suggest an enhancement. We have one player that plays more than the others, so he is always at the top of the leaderboard for sessions and deaths. It would be great if instead of just the top 1 for each category, we could have a ranked list, like a top 5. I suppose you could make the number of entries to display configurable as well.

**Comment by thedefside** [comment]
Wow, thank you!

**Comment by nwesterhausen** [comment]
Added rankings to leaderboard. Default is 3, configurable up to any number you want.

Released in version 1.3.0
