### ISSUE TITLE
Feature Request - a reload config command (in chat or console) OR an option to detect changes

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#61]
It would be nice if the config files could be reloaded via chat or console

example in chat:
!dcreload
(admin only)

OR a configurable option to detect file changes (maybe doesnt load change if bad config?)

I am going through editing messages & hate that I have to restart the server on my players if I want to see a change

**Comment by nwesterhausen** [comment]
Yeah something like that doable. Might just make it a single toggle for simplicity "Check for config updates every hour"

**Comment by nwesterhausen** [comment]
Config should be reloaded when it detects a change.
