### ISSUE TITLE
Feature Request: Use the player steamId instead of the name to identify records

### ISSUE THREAD

**Issue by thedefside** [nwesterhausen/valheim-discordconnector#68]
We change our character names often and this makes a new entry for each category on the leaderboards instead of adding to the existing record. Would it be possible to use the steamId to identify and increment existing records?

![image](https://user-images.githubusercontent.com/32403915/138376029-194c5786-f9a0-439c-a1af-d1068e05efa0.png)

**Comment by CruxCraft** [comment]
> We change our character names often and this makes a new entry for each category on the leaderboards instead of adding to the existing record. Would it be possible to use the steamId to identify and increment existing records?
> 
> ![image](https://user-images.githubusercontent.com/32403915/138376029-194c5786-f9a0-439c-a1af-d1068e05efa0.png)

Unless this was configurable, I feel as though this would hurt more servers than it would help...

We have players who role play multiple personalities. We also have players whose kids that turns on their accounts in addition to them playing. These area all separate players despite one account.

It is probably possible to edit the files to reconcile the different numbers, but a better alternate solution might be something like what OdinQOL does with this option:

chatPlayerName = 

It would allow your players to change their chat name while keeping the same in game name... might be helpful =]

I'm all for more options even if they break old things as long as they are configurable/optional

**Comment by thedefside** [comment]
Works perfectly! Thanks, @nwesterhausen !
